### ISSUE TITLE
Hot Drop: Turrets get 4 evasion pips on first turn

### ISSUE THREAD

**Issue by NickAragua** [CWolfs/MissionControl#125]
When doing a base attack and using the "safety" feature which gives initially deployed units the free evasion pips, turrets also get the evasion pips. 

Normally this isn't noticeable as it goes away after a turn, but the lance happened to get spawned within LOS of a base and saw the turrets right away, and boy were they hard to hit for some reason.

**Comment by NickAragua** [comment]
Update: looks like the turret evasion sticks around indefinitely?

**Comment by CWolfs** [comment]
Thanks for this report. I bad heard of reports of this since MC has been added to the RT alpha. I think it's just a plain MC bug/side effect as turrets don't ever move so guess they never lose their evasion.

I'll fix this. Thanks for reporting.

**Comment by CWolfs** [comment]
Fixed in `develop`.

**Comment by CWolfs** [comment]
Added new `settings.json` properties to control this behaviour.

Hotdrop settings now look as follows:

```json
  "HotDrop": {
    "Enable": true,
    "GuardOnHotDrop": false,
    "EvasionPipsOnHotDrop": 4,
    "IncludeEnemies": true,
    "IncludeAllyTurrets": false,
    "IncludeEnemyTurrets": false,
  },
```
