### ISSUE TITLE
Additional Lances: Comma based decimal locales caused rewards to be 100% higher

### ISSUE THREAD

**Issue by CWolfs** [CWolfs/MissionControl#269]
Comma based decimal locales caused rewards to be 100% higher. This is due to the default culture for the json deserialiser.

Where it might be 9% the bug would cause it to be 900% reward.

**Comment by CWolfs** [comment]
In `develop`.

**Comment by f-abel** [comment]
Default local is "C" and all others mods uses . as decimal separator without trouble.
May be your parser is "too" intelligent and consider the user local, 
Mine is LC_NUMERIC="fr_FR.UTF-8" using , as decimal you are right.
I'll try to run with LC_NUMERIC="C" 'too see'

I'll re-try the V1 : 1st attemp was not conclusive (will probably rise a new bug;)

**Comment by CWolfs** [comment]
The fix has been reported as not working. I need to investigate this more. I run the JSON parser as culture invariant so it shouldn't be going wrong.

**Comment by CWolfs** [comment]
I've put another attempted fix for this into `develop`. I'll see if this helps.

**Comment by CWolfs** [comment]
100% confirmed fix for this issue. It'll be in 1.0.4 and is currently in `develop`.
