### ISSUE TITLE
Assassinate: Contract autocompletes with enemies still on the board

### ISSUE THREAD

**Issue by CargoVroom** [CWolfs/MissionControl#290]
If all units spawned by the vanilla game are destroyed the mission ends even if there are Additional Lances units still active.

After destroying the target Assassinate activates an Extraction Point primary objective. The idea being you can get just the target and extract under fire. If there are no enemies left the contract autocompletes rather than forcing you to walk. This autocomplete ignores MC spawned units.

Example:
https://clips.twitch.tv/EnergeticAlertFalconChefFrank

This might apply to other contracts with a vanilla extraction zone.

**Comment by CWolfs** [comment]
Hey.

MC already supports solving this with `IsPrimaryObjective` settings.json setting. You'll need to add `Assassinate` to it. Here's what it would look like.

```
  "AdditionalLances": {
    // other settings
    "IsPrimaryObjectiveIn": ["SimpleBattle", "ThreeWayBattle", "Assassinate"],
```

**Comment by CWolfs** [comment]
After further feedback from Cargo it seems that this doesn't work in this usecase and will block the extraction so I will investigate.

**Comment by CWolfs** [comment]
So, there's a `AutoCompleteGameLogic` script that's on some contract types that control this autocomplete behaviour.

I did think `IsPrimaryObjectiveIn` would handle this. A primary objective must be completed for a contract objective (which holds one or more objectives) is classed as completed.

It's a subtle difference as this `AutoCompleteGameLogic` checks for specified objectives with a critera. If this critera is met, then it will run over a second list of objectives and set their specified status (usually 'completed').

So... out of this comes a new MC feature...

```
  "AdditionalLances": {
    ...more...
    "ExcludeFromAutocomplete": ["DefendBase", "FireMission"],
    ...more...
}

By default now, all AL lances must be destroyed before the autocomplete runs. If a contract type shouldn't have this logic, then it must be added to this `ExcludeFromAutocomplete` list.

**Comment by CWolfs** [comment]
In `develop`.
