### ISSUE TITLE
After mission completion, game locks going to pilot screen.

### ISSUE THREAD

**Issue by xeryx01** [CWolfs/MissionControl#418]
It doesn't happen very often but the game locks up after a completed mission going to the pilot screen, pretty frustrating to complete a mission, and the game locks up about 5-10% of the time, especially when you can't typically go back and reload combat saves.

I am attaching all the files I can think of to help.
[.modtek.zip](https://github.com/CWolfs/MissionControl/files/5436514/default.modtek.zip)
[20201026_01-26-28.zip](https://github.com/CWolfs/MissionControl/files/5436515/20201026_01-26-28.zip)
[output.zip](https://github.com/CWolfs/MissionControl/files/5436517/output.zip)

**Comment by xeryx01** [comment]
Here is another dump
[20210226_21-05-33.zip](https://github.com/CWolfs/MissionControl/files/6052783/20210226_21-05-33.zip)

**Comment by xeryx01** [comment]
Oops hit the wrong button.

**Comment by Cat-Lady** [comment]
This likes to happen for me - sometimes - even with absolutely vanilla game. Are you sure it is MC related?

**Comment by xeryx01** [comment]
Please check the log. It shows a critical error, but I have no idea if it is completely MC's fault as I am not a coder type.

**Comment by xeryx01** [comment]
OK I think I have the proof now, I disabled the BTPF stuff and it did lock up again going to the distribution screen. I have no Idea how MC does its stuff so I am only giving you my logs so hopefully, we can find the issue,
[20210312_19-09-05.zip](https://github.com/CWolfs/MissionControl/files/6132715/20210312_19-09-05.zip)

**Comment by CWolfs** [comment]
When I get around to fixing the Flashpoint issue, I'll take another look at this one.

**Comment by xeryx01** [comment]
I am still investigating this issue and trying to eliminate it as much as possible, but so far it has only happened when allied lances help me in a mission.

**Comment by xeryx01** [comment]
I have a new update and a bug with pathing, we can put it under a new one if you like.

`MessageCenter [ERROR] CRITICAL ERROR, PLEASE REPORT:
Delegate OnRecomputePathing - Standard for message type RecomputePathing failed with exception 
Object reference not set to an instance of an object
  at BattleTech.PathNodeGrid.ResetPathGrid (UnityEngine.Vector3 origin, System.Single beginAngle, BattleTech.PathingCapabilitiesDef pcd, System.Single maxDistance, BattleTech.MoveType moveType) [0x00239] in <4184af8dbeb44635831353f4d349631c>:0 
  at BattleTech.Pathing.ResetPathGridIfTouching (System.Collections.Generic.List`1[T] Rectangles, UnityEngine.Vector3 origin, System.Single beginAngle, BattleTech.AbstractActor actor) [0x0006b] in <4184af8dbeb44635831353f4d349631c>:0 
  at (wrapper dynamic-method) BattleTech.AbstractActor.OnRecomputePathing_Patch1(object,MessageCenterMessage)
  at MessageCenter.SendMessagesForType (MessageCenterMessageType messageType, MessageCenterMessage message) [0x00037] in <4184af8dbeb44635831353f4d349631c>:0 `

**Comment by xeryx01** [comment]
I am wondering if the original error was being caused by an incompatibility with cac and a newer version of the custom components. I am currently testing the version that is in cac.

**Comment by CWolfs** [comment]
I think this is still probably related to #382

**Comment by xeryx01** [comment]
OK, I will try this I have been doing the opposite

**Comment by xeryx01** [comment]
@CWolf, that is a tough one to remember, but I do know it has done it many times when I have had allies on the map. I have been playing for a while now, as much as I can, and since I changed out that custom components file I haven't crashed.  I also noticed that the game is not locking up[ on exit like it was doing, so maybe there was an issue with it.  I am still testing this though and will try and det a definititve anser this weekend.

**Comment by xeryx01** [comment]
I have played probably 30 missions this week trying to do every conceivable combo to get the battle not to transition to the debrief screen and I cannot get it to lock up anymore. I am pretty sure that the newer Custom Components had an incompatibility with CAC as Kmission said was the cause.  Maybe you can try it out as well to prove it. Otherwise, I would close this since no one else is reporting in on it.

**Comment by CWolfs** [comment]
Thanks for digging into it, @xeryx01. I've got not time to look into this so closing for now.

**Comment by xeryx01** [comment]
Well, I finally got it to do the crash, With Allies Present, the AI started following the convoy, but I do not think this is why it crashed. Here is the log and the Screenshot Please re-open the issue. Kinda pissed me off it happened! cuz I finally found a good custom Thunderbolt! Here are all my major logs.  Remember, I am just collecting data for you and I hope it helps because I too will be out of time to help.

[loot_magnet.log](https://github.com/CWolfs/MissionControl/files/6274688/loot_magnet.log)
[log_2021-04-07_14-42-34.xlsx](https://github.com/CWolfs/MissionControl/files/6274691/log_2021-04-07_14-42-34.xlsx)
[20210407_19-56-20.zip](https://github.com/CWolfs/MissionControl/files/6274684/20210407_19-56-20.zip)
[output.log](https://github.com/CWolfs/MissionControl/files/6274686/output.log)

**Comment by CWolfs** [comment]
Possible improvements added to `develop` in the v1.5 codebase for improving data cleanup.
