### ISSUE TITLE
Units not following, even though it says they are in console

### ISSUE THREAD

**Issue by xeryx01** [CWolfs/MissionControl#420]
I have noticed an issue with multi-phased missions.  Even though in the console it says a unit is set to follow, their behavior is not following **MY UNITS**,  They work just fine when the mission is started (not mission-related), but after an engagement ends they do not go back to follow the leading or heaviest target of my lance mech. Originally I thought it was settings being incorrect but it isn't because when you move on the map before an engagement they work just fine!

here are my new settings in my settingsmodpack.json 

  "AI": {
    "FollowPlayer": {
      "Pathfinding": "Alternative",
      "Target": "HeaviestMech",
      "StopWhen": "OnEnemyDetected",
      "MaxDistanceFromTargetBeforeSprinting": 60,
      "TargetZoneRadius": 90,
      "TimeToWaitForPathfinding": 60,
      "TicksToWaitForPathfinding": 20
    }

here is the log,
[output_log.txt](https://github.com/CWolfs/MissionControl/files/6239599/output_log.txt)
[output.log](https://github.com/CWolfs/MissionControl/files/6239666/output.log)
 as you can see everything is fine in the console, but I have been watching the movement of the tanks (for 8 turns and gave up)  It is as though the **Target 'Mech is being lost from the lead lance (mine) and being moved to one of their members in the lance.**   Then they just keep moving around each other, and will not follow me, until I go and detect an enemy!

Here is a pic

![Tanks00000](https://user-images.githubusercontent.com/45599120/113213855-ece0a780-9235-11eb-874e-49f026de6652.png)

**Comment by xeryx01** [comment]
After much long thought about this issue, I firmly believe the allies are not being reassigned properly is the cause of the crash in the other thread causing the logical and fatal error when leaving the battle.  It would be really great if other people could get involved and perform some Blackout Missions and watch for these abhorrent behaviors and see if the mission will crash afterward to confirm.

**Comment by CWolfs** [comment]
I discovered certain checks I was using `GetVisibleEnemyUnits` and `GetDetectedEnemyUnits` from the vanilla code were picking up dead units. I now filter out dead units and this fixes the problem.

**Comment by CWolfs** [comment]
In `develop` for release v1.5.

**Comment by xeryx01** [comment]
OMG!!! That is AWESOME!!! Can't wait! Great JOB! I bet that wasn't easy

**Comment by CWolfs** [comment]
Video showing things working.

https://youtu.be/zBhnTauFwV8
