### ISSUE TITLE
Additional Lances: Incorrectly treating `lanceExcludedTagSet`

### ISSUE THREAD

**Issue by hongooi73** [CWolfs/MissionControl#491]
Hi, thanks for your work on this mod. I noticed this error in the log after modifying the supplied lancedefs to exclude some of my manually defined lances:

> ERROR: Lance spawner Lance_Ally_Force_8977e287-c11e-470c-bf08-f4f0f5bf2dfb - (8977e287-c11e-470c-bf08-f4f0f5bf2dfb) could not find a lance to match these tags: [lance_type_battle, lance_type_medium, elite_arsenal, blackwidowcompany] and these excluded tags []. Falling back to just a difficulty choice.

It looks like it's trying to find a lance that matches the extra tags ("elite_arsenal", "BlackWidowCompany") rather than filtering them out.

Here is a snippet of the modified Generic_Battle_Lance.json:

```
{
  "lanceKey": "Generic_Battle_Lance",
  "lanceDefId": "Tagged",
  "lanceTagSet": {
    "items": ["lance_type_battle"]
  },
  "lanceExcludedTagSet": {
    "items": ["elite_arsenal", "BlackWidowCompany"]
  },
```

The only modification is the added `lanceExcludedTagSet` item.

**Comment by CWolfs** [comment]
Thank you for the bug report! You're completely right there's a problem there. I took a look at the code and I can see I'm setting the excluded tags and the normal lance tags with the excluded tags defined for Additional Lances. Great spot!

Quick fix - I'll put it in the next MC release.

![Bug](https://user-images.githubusercontent.com/7622361/153477339-946ca63c-499c-4664-b58f-e43a32b91bb1.png)

**Comment by CWolfs** [comment]
This fix is in `develop`. It'll be in the next MC release.

**Comment by hongooi73** [comment]
Thanks for the quick response!

Btw, I'm the maintainer for [Expanded Arsenal](https://www.nexusmods.com/battletech/mods/635), which I'm in the process of reworking. Do you mind if I add Mission Control to the modpack? It seems like the ideal way to add challenge to the endgame.

Thanks again!

**Comment by CWolfs** [comment]
No problem! It helps a lot when people make useful bug reports.

Very cool. I just saw your release on Reddit - congrats! Sure, feel free to use MC as part of your pack. I designed it in a way to try and help modpacks out as best I can. I'm not sure if you know but you can set up a 'settings.modpack.json' at the same level as your 'settings.json' file and that modpack.settings.json will override any settings. You don't need to include all the settings - just the ones you want to override.

Feel free to join the discord if you need to ask questions. Good luck!
