### ISSUE TITLE
Objective will not complete: Mission Breakout; Type: Attack and Defend for Faction Pirate

### ISSUE THREAD

**Issue by christianerding2** [CWolfs/MissionControl#505]
Small contract issue:
When Mission Control is activated, the objectives will not complete when the last building of the enemy base is destroyed.
If buldings are not destroyed no reinforcement lance will not arrive and the mission can not completed this way, too.

But Fantastic Mod anyway.

Sincerly, Christian

**Comment by CWolfs** [comment]
Thanks for the report. I'll check this out. Do you have any more information on your setup? Do you run any modpacks? Were there any Additional Lances (e.g. Support Lances)?

**Comment by christianerding2** [comment]
Hello CWolf,

thx for your fast answer and time.
Most important and hopefully most helpfull information first:

When I save before I destroy the last building and deactivate mission
control, the objective will complete.


My system runs on 16 Gb Ram and a GeForce 1080.

I run mission control and bigger drops, but I am not far enough in the game
to drop with more than 4 Mechs. So I have one lace with 4 Mechs.

My other mods:
  "AdjustedMechAssembly",
  "AdjustedMechSalvage",
  "Advanced Difficulty Settings",
  "AlternativeReputation",
  "BTRandomMechComponentUpgrader",
  "Commander_Background_and_Quirks",
  "Custom Ammo Categories",
  "CustomComponents",
  "CustomLocalization",
  "CustomVoices",
  "DontShootTheDead",
  "Flashpoint_Fighting_Ghosts",
  "FlashpointSpawnAdjustments",
  "Give_me_Death",
  "Give_them_Kell",
  "HMFlashpointFix",
  "InjuriesHurt",
  "IRBTModUtils",
  "IttyBittyLivingSpace",
  "JB_View_Distance_Inc_Rev3.0",
  "LessHeadInjuries",
  "LootMagnet",
  "MeleeMover",
  "MightyChargingJuggernaut",
  "Mission Control",
  "ModTek",
  "Monthly Tech Adjustment",
  "More Knockdowns-101-1-0",
  "NoTimeToBleed",
  "PanicSystem",
  "PermanentEvasion",
  "Pilot Quirks",
  "PilotHealthPopup",
  "ProtectTheMechs",
  "Repair Bays",
  "Retrainer",
  "SkipIntro",
  "StabilePiloting",
  "StabilityTonnage",
  "TurretlessVehicleHits",
  "VehicleImprovementProject",
  "VIPResizer",
  "Weapons_RW",
  "BiggerDrops",
  "CustomActivatableEquipment"

Keep Up the good work!

Sincerly, Christian






Richard Griffiths ***@***.***> schrieb am So., 22. Mai 2022,
23:16:

**Comment by christianerding2** [comment]
Hello CWolf,

sorry for sending so much information to you.
I am not a professional like you, but I think I found the reason for the bug in output.log

"MissionControl [LOG] [MissionControl] No contract MC settings override found for 'AttackDefend_Pirate_Breakout'."

I hope this makes it easier to fix, or is there a way how I can fix it?

Sincerly,

Christian

**Comment by CWolfs** [comment]
Thanks for the info @christianerding2. That last message is fine and expected. MC allows for players and modders to provide contract specific overrides to do special things - that message just means it doesn't have one - but that's fine.

**Comment by christianerding2** [comment]
[output.log](https://github.com/CWolfs/MissionControl/files/8757855/output.log)

Just for additional information.

**Comment by hongooi73** [comment]
I think I've seen this before. Some A&D missions seem to have special code where a couple of allied reinforcement lances will drop at completion. This fouls up the usual logic for ending the mission immediately after you kill everything. If you go to the evac zone, the lances should drop and the mission will then end.

**Comment by christianerding2** [comment]
In the of this pirate-contract you have to destroy 4 buildings or a total
of 3 reinforcements lances will drop with a delay of a few rounds. But with
mission control:
The message from Darius when you attack the first building will not
trigger. When the timer for the reinforcement lance will trigger, the
lances will not spawn. Lastly the "Future Evac Point" will never change to
"Evac Point"

Hong Ooi ***@***.***> schrieb am Di., 24. Mai 2022, 22:39:

**Comment by xeryx01** [comment]
Can you post your settings for BattleTech Performance Fix? In my experience, it is what causes missions to not complete. I have run these missions in XAI without fail.

**Comment by christianerding2** [comment]
Thx for the advice. I already did. Not using mission control make the mission complete always. Looks like the problem is in the combat-save. On reload things screw up. I disabled everything in mission controll to not stress the game, just wanted to have a bigger lance with "Bigger drops" but so far no solution.

**Comment by hongooi73** [comment]
Wait, are you reloading from a save in the middle of a mission? Don't do that. The in-game save is notoriously unreliable, to the point that there's a mod that disables it to keep it from screwing up other mods.

**Comment by CWolfs** [comment]
@hongooi73 is correct. Mission Control is not compatible with combat saves and loads. Basically never do it otherwise things break.

This goes for all the big mods.

**Comment by christianerding2** [comment]
This is sad news. The published mod list is the one I use for a long time now on several playthroughs. I am using combat saves a lot, escpecially when headhunting for rare mechs. I never had a corrupt save, only exception is when you make a combat save in the round in which a enemy is sonsor-locking you.
I love mission control, but is there a kind of "killswitch" which disables the mod but, keeps the basic framework of mission control running, so "Bigger drops" is usable? (Then my dream that even combat-saves are working come true! ;-)

**Comment by CWolfs** [comment]
You can turn almost all the features in the MissionControl folder under 'settings.json'. The feature to allow for BiggerDrops will still work.

I had put in some work to make MC save compatible - that's why it sometimes works. The more features you disable the higher chance things will be ok.

I would love to make the save compatibility better but all my energy is in the Mission Control contract type Designer at the moment.

**Comment by christianerding2** [comment]
I could not more agree. There is so much effort and skill in this mod. Save compatiblity was much better than expected, most missions have working combat-saves. And because I am "Mr. Save&Load" I should know. ;-) As always, thx for the helpfull tips.

**Comment by CWolfs** [comment]
I'm going to close this issue as it's very likely the save issue we discussed. Let me know if it needs to be reopened.
