### ISSUE TITLE
Additional mechs are not saved on mission screen

### ISSUE THREAD

**Issue by christianerding2** [CWolfs/MissionControl#506]
Rather small issue, maybe it can be solved in the settings, but I could not find out how:
I use bigger drops and mission control I upgraded the argo with more dropslots.
Everything fine so far. But before every new mission I need to place pilot and mech in the additional slots again, they are not saved like the first four pilots and mechs.
Is there a setting to fix this, or is this a "bug"?

**Comment by CWolfs** [comment]
Pretty sure that's just Bigger Drops not remembering what units/pilots go into what slots. It's not a Mission Control issue.
