### ISSUE TITLE
UI: Contract selection - obscured description

### ISSUE THREAD

**Issue by AlfredBroda** [CWolfs/MissionControl#514]
When having an additional lance the UI elements during contract mech/pilot selection obscure the pop-up for "VIEW DETAILS", making it very difficult to close. The Close button is overlaid and mostly not interactable despite being visible - only a small top portion is usable. 
I don't know if this is related to slots being LOCKED or not.
![obraz](https://user-images.githubusercontent.com/1722691/178240212-cd2a52f3-b0e4-47d6-beb5-30a412b62b3d.png)

**Comment by CWolfs** [comment]
Thanks for the issue, however, this is not a Mission Control issue. It's a bigger drop issue and that's a different mod. 

https://github.com/BattletechModders/BiggerDrops

Closing this.
