### ISSUE TITLE
Additional Lances: Reinforcement Evasion 

### ISSUE THREAD

**Issue by xeryx01** [CWolfs/MissionControl#517]
I know we have had multiple talks about evasion happening, and you have made clear that it is only supposed to happen during initial deployment.  XAI has been greatly refined and I have had the help of XSNomad to verify the code I have been using does not contain ANY evasion changing code as XAI strictly uses the vanilla evasion stripping system for AI purposes. 

To prove that no Hot Drop Protection (HDP) is active in my mod, I disabled Mission Control on multiple missions that typically have reinforcements dropped, this includes Base Defense missions and also Ambush Convoys.  With MC enabled and HDP on or OFF it doesn't matter for the reinforcements. The initial HDP works properly as it is designed and that is not the issue. However, the GAME must be picking up MC code somehow because when reinforcements are deployed this happens. 1 ) On the initial landing they do not have any HDP setting they are not guarded and do not have any evasion pips.  (which according to Cwolf is impossible to happen because the code only works at the beginning of the mission),The BUG/Problem is once they move, even if only a few hexes, they receive 6 additional evasion PIPS (on top of the movement pips) making them impossible to hit until the next round, and if dropped behind you well then you might as well just run and abort the mission.

To be clear, I have tested this happening for over 10 hours over two days to try and isolate the exact cause. However, even when I completely disable HDP in MC in all the settings files. it still happens! which seems impossible to me. The only way I know it is mission Control is by disabling it and running many missions with all other XAI mods activated. For a bit, I thought it might be CAC but is not. I have screenshots and logs with proof if needed.  Unfortunately, I am not a coder and I really did try to isolate it for you but it just defies logic, much like the Allied lances defy their follow orders.

**Comment by CWolfs** [comment]
@xeryx01 When we chatted about this I asked you to give me an exact contract type and contact I can test this on. Can you give me one please?

**Comment by hongooi73** [comment]
I'm pretty sure this is a bug in the base game. I ran into the same problem 2 years ago without any mods:

![](https://i.imgur.com/x9EqtAH.png)

**Comment by CWolfs** [comment]
@hongooi73 I've looked into this issue in the MC codebase in the past and I never see how this could be caused by MC so I'm very inclined to believe it's a vanilla issue.

Regardless, it'll be a low priority thing to investigate at this point.

**Comment by xeryx01** [comment]
@Cwolf, very interesting what hongooi72 shows and says?? I have not had it happen with vanilla that I have seen even before I incorporated MC into XAI, I never saw it. So I take it Vanilla has hot drop protection hidden somewhere? if so maybe I can have someone else patch it.

**Comment by xeryx01** [comment]
> I'm pretty sure this is a bug in the base game. I ran into the same problem 2 years ago without any mods:
> 
> ![](https://camo.githubusercontent.com/bbf1cce10e579f191b579f17f068b9c05a9a516dfaa2e154a43f3e35559c145f/68747470733a2f2f692e696d6775722e636f6d2f783945717441482e706e67)
> 
> That's a Bull Shark from a reinforcement lance with more evasion than is possible. No mods were loaded.

Thank you very much for your input!

**Comment by xeryx01** [comment]
This is one of them

AmbushConvoy_Pirate_WeaponShipment

**Comment by xeryx01** [comment]
This is a Vanilla bug
