### ISSUE TITLE
Bug. Probably.

### ISSUE THREAD

**Issue by BrightCard** [CWolfs/MissionControl#561]
I've been using your 1.4.1 mod for a while, and it was great. When notified that MC 1.4.1 was out of date, I deleted the old file, and installed 1.5.1.

But 1.4.1 didn't delete from the "Mods" page in Battetech. And 1.5.1 won't appear. When the 1.4.1 box is checked on the Mods page, I can't get any battle to start in the game at all. When the box is unchecked, the game works... but without the mod (obviously).

I've tried reinstalling Battletech from scratch, including all mod files, and re-downloading the mods... but that didn't help at all.

I suspect this is an artifact of the Steam workshop, but I have no clue how to delete/fix the issue. Any suggestions?

Thanks!

**Comment by CWolfs** [comment]
Are you using ModTek or the HBS mod system? Do you have any logs you can provide me? Thanks.

**Comment by BrightCard** [comment]
Neither ModTek nor HBS. Only mods I've used/downloaded are download=>unzip to "Mods" folder; all mods are from Nexus (I unzip files using PeaZip, if it helps). I don't even recall how I got your original 1.4.1 downloaded. Probably the same way, but my memory is fuzzy on such things.

I wish I had logs to give, but I'm not _that_ tech savvy. All I know, is that the game freezes with an infinitely spinning download timer. No error messages, no warnings, nil. Oh, and the Task Manager indicates that Battletech is "Not Responding"

If it helps, here's the path I have to your file in the Battletech mods folder: C:\Program Files (x86)\Steam\steamapps\common\BATTLETECH\Mods\MissionControl

I can send you a list of my other current mods, if it helps.

Oh, FYI I have one other "broken" mod that won't erase/doesn't function: BTModSample. Hopefully that's a clue?

Thanks! Even if you can't ultimately help, it's still nice to get a response.

**Comment by CWolfs** [comment]
Sounds like you're using the HBS mod loader without realising it. MC no longer supports that inbuilt modloader so best to use Modtek.

- First, delete your `C:\Program Files (x86)\Steam\steamapps\common\BATTLETECH\Mods\MissionControl` folder as the upgrade from 1.4.x to 1.5.x doesn't support copying and overwriting the whole folder (some files were renamed so need to be deleted). 

- If there's a `C:\Program Files (x86)\Steam\steamapps\common\BATTLETECH\Mods\.modtek` folder - then delete that. It's a cache folder so should be cleared just to be safe.

- Go to the ModTek github and download probably v2 (v3 is still under a lot of development and not sure how stable it is) -https://github.com/BattletechModders/ModTek/releases/download/v2.0.6/ModTek_2.0.7.zip

- Double-click and run the `ModTek/ModTekInjector.exe`

Now you should be able to run into the game and things should work.

If you still have trouble go to `C:\Users\Rich\Documents\My Games\BattleTech\mods` and make sure there is no Mission Control mod folder in there.

**Comment by BrightCard** [comment]
I think that did it! The game now runs properly (so far), and the two error/empty mods are gone. Everything downloaded as you said, and looks correct in all the right place. 

Side notes: I believe I was downloading the ModTek loader incorrectly. Also, I had no idea there was a Users\username Battletech folder: I deleted everything in that Mods sub-folderfolder. Cleared up the BTSMod error as well.

It all looks good; if I have any further issues pertaining to your mod, (I doubt it), I'll let you know. 

Thank you again!

**Comment by CWolfs** [comment]
Glad to hear it's working now.
