### ISSUE TITLE
Additional Lances: Restrict extra lance spawns on flashpoint missions

### ISSUE THREAD

**Issue by NickAragua** [CWolfs/MissionControl#80]
Some flashpoint missions have tonnage restrictions, or it doesn't really make narrative sense for extra allied lances to spawn in them, or (in one case) limit you to dropping a single mech. As it turns out my one guy in a Centurion couldn't go 1 on 9 with enemy mechs (although he did take down two and nearly cored a third.)

Is it possible to prevent extra lances from spawning on flashpoints missions or some subset of them?

**Comment by CWolfs** [comment]
That's a very good observation. While MC works with flashpoints I haven't really had any time yet to tweak it for FPs. Just had time to make it BT v1.3 / FP compatible.

I'll definitely make this type of thing a high priority for the MC v0.3.0 release. I'll just finish off v0.2.0 quickly after Christmas.

Thanks for the suggestion. It's very helpful.

**Comment by CWolfs** [comment]
I'm looking to see if I can squeeze this quickly into the `v0.2.0` release. I've finished all features and planned bugs but this one might be a quick one with a high impact.

**Comment by CWolfs** [comment]
For `v0.2.0` I've added `DisableIfFlashpointContract` which defaults to `true`. For v0.3.0, I will add more grandular control over this for flashpoints so you can specify some more rules like if you're limited to 1 mech - don't use Additional Lances etc.
